---
grails:
    profile: web
    codegen:
        defaultPackage: rdmdt
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
#            dbCreate: create-drop
#            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/rdmdt
            username: postgres
            password: adminadmin1
            pooled: true
            driverClassName: org.postgresql.Driver
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/rdmdt
            username: postgres
            password: adminadmin1
            pooled: true
            driverClassName: org.postgresql.Driver
---
grails:
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: rdmdt.User
                authorityJoinClassName: rdmdt.UserRole
            authority:
                className: rdmdt.Role
            successHandler:
                alwaysUseDefault: true
                defaultTargetUrl: /index/index
            ui:
                encodePassword: false
                password:
                    minLength: 8
                    maxLength: 64
    databinding:
            dateFormats: ['yyyy-MM-dd','dd-MM-yyyy','MMddyyyy', 'yyyy-MM-dd HH:mm:ss.S']

environments:
    development:
        uploadFolder: C:/Users/nasullah.alham/Desktop/upload_folder/
    test:
        uploadFolder: C:/Users/nasullah.alham/Desktop/upload_folder/
    production:
        uploadFolder: C:/Users/BRC15Admin/Documents/upload_folder/

---
server:
    contextPath: '/RDMDT'
    compression:
          enabled: true

---
---
environments:
    development:
        grails:
            serverURL: http://localhost:8080/RDMDT
    test:
        grails:
            serverURL: http://localhost:8080
    production:
        grails:
            serverURL: http://oxnetbrc15.oxnet.nhs.uk:8080/RDMDT

---
 grails:
     controllers:
         upload:
             maxFileSize: 50000000
             maxRequestSize: 50000000